### ISSUE TITLE
FCGI: fullreadfd: hangup (terminating)

### ISSUE THREAD

**Issue by sammyj85** [kristapsdz/kcgi#53]
I am using Linux 4.8, and have added CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER.
I am using kcgi 0.10.7 connecting to Hiawatha 10.3 web server. I can get it working in CGI form, but not as FastCGI. I am using the tutorial0 and tutorial2 codes.

    # kfcgi -p / -d -v -n 1 -N 1 -- /var/www/fcgi-bin/web-gui-backend                      
    fcgi.c:754: fullreadfd: hangup (terminating)
    wrappers.c:185: child signal 31
    wrappers.c:185: child signal 31
    kfcgi[380]: worker unexpectedly exited

It seems to be getting stuck in wrappers.c:649, in fullreadfd(). recvmsg is only returning 0 bytes from the socket.

    } else if ((rc = recvmsg(fd, &msg, 0)) < 0) {
        XWARN("recvmsg");
        return(-1);
    } else if (0 == rc)
        return(0);    <<<<<< doing this return

For what it's worth, hiawatha.conf looks like this:

    FastCGIserver {
        FastCGIid = FCGI 
        ConnectTo = /var/www/run/httpd.sock
        Extension = cgi
    }
    UseFastCGI = FCGI
    ExecuteCGI = yes

**Why could it be having trouble using the UNIX file socket?**
I am using a simple stripped-down Linux that only has the root user.

Adding "-s /var/www/run/httpd.sock" to kfcgi makes no difference.

The httpd.sock file does not exist when hiawatha is started up. It does appear when kfcgi is run and exits on failure. **Who is supposed to be creating the socket file? kfcgi or the web server?**

**Also, who sets the filesystem jail?** Do we chroot ourselves first? Or does kfcgi do it internally? (The doc seems to suggest the second.) For me, kfcgi does not seem to do it.
/var/www/fcgi-bin/web-gui-backend does of course exist.

    # kfcgi -d -v -n 1 -N 1 -- /fcgi-bin/web-gui-backend
    kfcgi[368]: execve: /fcgi-bin/web-gui-backend: No such file or directory
    kfcgi[367]: worker unexpectedly exited

    # kfcgi -d -v -n 1 -N 1 -- /var/www/fcgi-bin/web-gui-backend                         
    kfcgi[372]: execve: /var/www/fcgi-bin/web-gui-backend: No such file or directory
    kfcgi[371]: worker unexpectedly exited

    # kfcgi -p / -d -v -n 1 -N 1 -- /var/www/fcgi-bin/web-gui-backend
    (This now runs)

**Comment by sammyj85** [comment]
Actually, I turned off CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER in the kernel, and it no longer displays errors! (Except: sandbox-seccomp-filter.c:287: prctl(PR_SET_SECCOMP): Invalid argument)
I realised I tested CGI mode before enabling the kernel config. So that works with CONFIG_SECCOMP off and also fails with CONFIG_SECCOMP turned on.

**Does anyone have any experience with why CONFIG_SECCOMP in the Linux kernel makes it fail?**
The question still remains about the filesystem jail, because that still behaves the same.

**Comment by xse** [comment]
Hey, 
kfcgi is creating the socket in my case with `kfcgi -d -U www-data -u www-data -s /run/kfcgi.sock -p / -- /srv/test/test.cgi`

For the `fcgi.c:754: fullreadfd: hangup (terminating)`, it might be a sandbox issue, you mentioned that you're using a simple stripped-down Linux that only has the root user, i assume it's an arm box or things like that, this issue is related to the name of the syscall used.

there's a -DSANDBOX_SECCOMP_DEBUG to uncomment in the makefile that might helps you get more meaningful outputs like : `ssh_sandbox_violation: unexpected system call (arch:0x40000028,syscall:221 @ 0x76e0f0a4)`

In that specific error the syscall is 221, which is  

> 221	common	fcntl64	sys_fcntl64	sys_oabi_fcntl64

In [sandbox-seccomp-filter.c](https://github.com/kristapsdz/kcgi/blob/master/sandbox-seccomp-filter.c) you'll find a list of allowed syscalls, some architectures have different names for those, for example :

```
#ifdef __NR_fcntl64 /* only noted on arm */
	SC_ALLOW(fcntl64),
#endif
```
This is architecture specific (between arm abi and eabi for example some syscalls have different names), you need to find out which syscall make it crash, what's the name of this syscall on your architecture, and add that syscall to the [sandbox-seccomp-filter.c](https://github.com/kristapsdz/kcgi/blob/master/sandbox-seccomp-filter.c) file.

Anyway, be aware i'm not sure about all this but i mean you can always try and this if that'll fix the issue.

**Comment by kristapsdz** [comment]
Addressing the seccomp part: please uncomment the -DSANDBOX_SECCOMP_DEBUG line in the GNUmakefile and recompile (make clean ; make).  This will tell you exactly what failed.

**Comment by kristapsdz** [comment]
As for the warning, I think that the test for seccomp is not working.  Can you please disable seccomp and check the line that ./configure prints regarding seccomp-filter?  It should say "no" when not working and "yes" when working.

**Comment by kristapsdz** [comment]
As for your jail, does the script execute when run with just chroot?  Is it statically linked?  That error doesn't just mean that the binary isn't found.  It means:
"The file filename or a script or ELF interpreter does not exist, or a shared library needed for file or interpreter cannot be found."

**Comment by sammyj85** [comment]
Thanks for the responses! I'm halfway there now.
I turned on the SANDBOX_SECCOMP_DEBUG, but that gave no extra output in this case. However, I am indeed cross-compiling the kcgi library, so it turns out that configure set the SECCOMP_AUDIT_ARCH for the host machine, and not the target! If I manually set the architecture to ARM, then it fixes all seccomp warnings.

Secondly, it is clear that kcgi is the one creating the socket file and setting the filesystem jail.
I had trouble with linking statically.. as in "gcc -static" still depended on most of the dynamic libraries, even though static versions of the libraries were alongside the dynamic ones. Indeed, the "file not found" error was meaning the loader was not found. After copying /lib/ld-linux.so.3 to the new root directory, then it was showing sensical error messages with other shared libraries files that were missing.

At this point, it does not print any error messages, and starts up fine. But it also isn't communicating. I'm still investigating this. Thanks for your help.

**Comment by sammyj85** [comment]
It turns out that my assumption that the Linux system was stripped down to only have the root user was wrong, haha. It indeed has users, so setting kfcgi and Hiawatha server to both use www-data user overcame the socket file permissions issue that was blocking communication.
Thanks for your help!
