### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by Citrullin** [kristapsdz/kcgi#59]
I have no idea what that actually means. The /tmp folder is there, it also create a demo_app.sock file

```
root@orangepizero:/etc/demo_app# kfcgi -s /tmp/demo_app.sock -p /var/www -- /var/www/fcgi-bin/app
daemon: Bad file descriptor
```

**Comment by ibonso** [comment]
Hello,
I am not an expert, but I also found problems trying to make kfcgi start.
In this case, I think you are setting the root of aplication to /var/www (-p parameter). Socket path also have to be relative to /var/www (I think).

I manage to make it work setting -p to '/'. My initial script is:
sudo kfcgi  -d  -v -r -n 2 -N 100 -w 10 -s/var/www/socket -u www-data  -U ibon -p/ -- /var/www/sample-fcgi  /var/www/froga2.db  ibon ibon

**Comment by ibonso** [comment]
I think chroot directory needs to include all your program dependencies (dinamic libraries). I tried to add depencies statically to de program but it didnt work anyway.
By

**Comment by Citrullin** [comment]
@ibonso How am I suppose to add pthread statically?

**Comment by ibonso** [comment]
The pthread library, has the static version an dinamic one. 
/usr/lib/x86_64-linux-gnu/libpthread.so
/usr/lib/x86_64-linux-gnu/libpthread.a

When I build my fcgi module, Im using this make rule:

LIBCPP = /usr/lib/gcc/arm-linux-gnueabihf/4.9.2/libstdc++.a
...
sample-fcgi: sample-fcgi.o rcf-proxy.a libkcgi.a 
	$(CC) $(DEBUG) -static -Wall -pthread sample-fcgi.o  libkcgi.a  libsqlite3.a libkcgihtml.a rcf-proxy.a -lz $(LIBCPP)  -lcrypto  -lsqlite3  -ldl -lm -o $@
...

I am not completly shure if this  includes  libpthread.a with my code. Anyway, I give up running my app in /var/www (chroot-ed with -p),  so is not so important for  me, even though I try to link everything statically.

**Comment by kristapsdz** [comment]
This issue seems to be a problem in compiling your software or building your chroot, so I'm closing it out as it's not related to kcgi.  I run statically-linked (and dynamically-linked with a properly-populated chroot) binaries all the time with kfcgi on Linux, FreeBSD, and OpenBSD.  (With or without **-d**.)

These days you should be using `pkg-config --static --libs kcgi`, or in your case, `pkg-config --static --libs kfcgi-html sqlite3`.  This will pull in all the required libraries.

If you run into this problem, I need to know (1) what system you're using (distro, glibc, musl, etc.), (2) how you obtained kcgi, (3) how you compiled your software, (4), what your chroot directory looks like.
