### ISSUE TITLE
Number of worker processes is 3 times the requested number

### ISSUE THREAD

**Issue by sammyj85** [kristapsdz/kcgi#60]
I have only need for a low volume of requests, and in fact there is a bottleneck in the next link in the chain (for simplicity of design) which the FCGI backend passes on to. So I have need for only one worker process.

Therefore I call kfcgi with -n 1 (I see the -N is useless without -r). However, it launches 3 worker processes. If I use -n 4, I get 12 workers.

Why is it doing something other than what I requested? It would be nice to not have the other processes using up memory when they are not used, as well as simplifying knowing which process ID is the active one, for potential debugging purposes (which doesn't seem to work yet, but that's a separate issue to investigate).

**Comment by kristapsdz** [comment]
I'm closing this because this is literally documented on the front page of the kcgi site.  It is doing exactly what you requested: each worker splits into its required components of a connection delegator, an HTTP parser, and your application.  You can see that in the "Implementation Details" of the website.  If you want to have the application process labelled, then I'm happy to accept patches that have a portable setproctitle() so as to delineate the delegator, parser, and application logic processes.
