### ISSUE TITLE
valgrind reports fullreadfd: hangup (terminating)

### ISSUE THREAD

**Issue by sammyj85** [kristapsdz/kcgi#61]
I'm interested in running valgrind on my FCGI application. I have kcgi v0.10.10.

I am able to run `sudo kfcgi -p / -s /var/www/run/httpd.sock -d -v -n 1 -u www-data -U www-data -- /var/www/fcgi-bin/fcgi-app`, which works fine (never mind the filesystem jail being set to / for this purpose).

However, I prepend it with `sudo valgrind --leak-check=full --trace-children=yes`, and it fails:

    fcgi.c:689: fullreadfd: hangup (terminating)
    wrappers.c:185: child signal 31
    wrappers.c:185: child signal 31

It seems to suggest it's having trouble accessing the socket, possibly a permissions issue. Has anyone had successing with using valgrind?

**Comment by kristapsdz** [comment]
This is because you're running Linux with seccomp in valgrind---it has nothing to do with kcgi.  Valgrind disables seccomp such that invoking `prctl()` will raise a SIGSYS (31), killing the process.

The solution is to compile your software without `HAVE_SECCOMP_FILTER`.  You can do this by having a *configure.local* with `HAVE_SECCOMP_FILTER=0` in it and running `./configure` (you'll see `seccomp-filter: manual (HAVE_SECCOMP_FILTER=1)` in the script output).  Or just edit *config.h* prior to compiling.
